sudo: required
dist: trusty
language: node_js
node_js:
  - "8.11.3"
env:
  global:
    - GH_REPO: github.com/FCC-Shanghai/fcc-sha.git
    - USER_NAME: 'jeremywu'
    - USER_EMAIL: 'wqx591449570@gmail.com'
    - DEPLOY_BRANCH: 'master'
install:
  - npm install
script:
  - npm run build
after_script:
  - sh ./deploy.sh